version: '3.8'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - server-john
      - server-paul
      - server-george
      - server-ringo
    ports:
      - "3000:80"

  server-john:
    build: ./whiteboard-server
    links:
      - redis
    expose:
      - "3000"
    environment:
      - NAME=John

  server-paul:
    build: ./whiteboard-server
    links:
      - redis
    expose:
      - "3000"
    environment:
      - NAME=Paul

  server-george:
    build: ./whiteboard-server
    links:
      - redis
    expose:
      - "3000"
    environment:
      - NAME=George

  server-ringo:
    build: ./whiteboard-server
    links:
      - redis
    expose:
      - "3000"
    environment:
      - NAME=Ringo

  client:
    build: ./whiteboard-frontend
    links:
      - nginx

  redis:
    image: redis:alpine
    expose:
      - "6379"