version: '3.8'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - server-john
      - server-paul
      - server-george
      - server-ringo
    ports:
      - "3000:80"

  server-john:
    build: ./whiteboard-server
    links:
      - redis
    expose:
      - "8883"
    environment:
      - NAME=John
      - PORT=8883

  server-paul:
    build: ./whiteboard-server
    links:
      - redis
    expose:
      - "8883"
    environment:
      - NAME=Paul
      - PORT=8883

  server-george:
    build: ./whiteboard-server
    links:
      - redis
    expose:
      - "8883"
    environment:
      - NAME=George
      - PORT=8883

  server-ringo:
    build: ./whiteboard-server
    links:
      - redis
    expose:
      - "8883"
    environment:
      - NAME=Ringo
      - PORT=8883

  client:
    build: ./whiteboard-frontend
    expose:
      - "3000"
    links:
      - nginx

  redis:
    image: redis:alpine
    expose:
      - "6379"