version: '3.8'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - server-1
      - server-2
      - server-3
      - server-4
    ports:
      - "3000:80"

  server-1:
    build: ./whiteboard-server
    links:
      - redis
    expose:
      - "3000"
    environment:
      - NAME=1
      - PORT=3000

  server-2:
    build: ./whiteboard-server
    links:
      - redis
    expose:
      - "3000"
    environment:
      - NAME=2
      - PORT=3000

  server-3:
    build: ./whiteboard-server
    links:
      - redis
    expose:
      - "3000"
    environment:
      - NAME=3
      - PORT=3000

  server-4:
    build: ./whiteboard-server
    links:
      - redis
    expose:
      - "3000"
    environment:
      - NAME=4
      - PORT=3000

  client:
    build: ./whiteboard-frontend
    expose:
      - "3000"
    links:
      - nginx

  redis:
    image: redis:alpine
    expose:
      - "6379"