apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: server-1
  name: server-1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server-1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: server-1
    spec:
      containers:
        - env:
            - name: NAME
              value: "1"
            - name: PORT
              value: "3000"
          image: server-1
          name: server-1
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
